### ISSUE TITLE
:question

### ISSUE THREAD

**Issue by araguaci** [Rocketseat/youtube-challenge-grpc#1]
❓ on hidra ❓
[nodemon] starting `node src/index.js`
E0311 13:35:00.115000000 15912 server_chttp2.cc:40] {"created":"@1583944500.115000000","description":"No address added out of total 1 resolved","file":"t:\src\github\grpc-node\packages\grpc-native-core\deps\grpc\src\core\ext\transport\chttp2\server\chttp2_server.cc","file_line":394,"referenced_errors":[{"created":"@1583944500.115000000","description":"Failed to add port to server","file":"t:\src\github\grpc-node\packages\grpc-native-core\deps\grpc\src\core\lib\iomgr\tcp_server_custom.cc","file_line":404,"referenced_errors":[{"created":"@1583944500.115000000","description":"Failed to listen to port","file":"t:\src\github\grpc-node\packages\grpc-native-core\deps\grpc\src\core\lib\iomgr\tcp_uv.cc","file_line":72,"grpc_status":14,"os_error":"address already in use"}]}]}

**Comment by jpedroschmitz** [comment]
As it is not related to the repository itself I am going to close this issue.
